apps:

  heimdall:
    enabled: true

  organizr:
    enabled: true

  pihole:
    enabled: true
    valuesOverrides:
      privileged: true
      serviceDns:
        nodePort: 31999
        mixedService: true
