{{- if .Values.apps.ddnsRoute53.enabled -}}

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ddns-route53
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: core
  source:
    repoURL: https://github.com/dom38/homelab.git
    targetRevision: main
    path: helm-charts/ddns-route53

  destination:
    server: https://kubernetes.default.svc
    namespace: ddns-route53

  # Sync policy
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true 
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    retry:
      limit: 3
      backoff:
        duration: 30s
  revisionHistoryLimit: 3

{{- end -}}
