{{- if .Values.apps.nextcloud.enabled -}}

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nextcloud
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  project: core
  source:
    repoURL: https://nextcloud.github.io/helm/
    targetRevision: 3.3.3
    chart: nextcloud
    helm:
      values: |
        {{- .Values.apps.nextcloud.valuesOverrides | toYaml | nindent 8 }}

  destination:
    server: https://kubernetes.default.svc
    namespace: nextcloud

  # Sync policy
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true 
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    retry:
      limit: 3
      backoff:
        duration: 30s
  revisionHistoryLimit: 3

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nextcloud-ingress
  namespace: nextcloud
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/whitelist-source-range: 87.75.106.7/32,192.168.128.1/32
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite ^/\.well-known/carddav https://$server_name/remote.php/dav/ redirect;
      rewrite ^/\.well-known/caldav https://$server_name/remote.php/dav/ redirect;
spec:
  tls:
  - hosts:
    - nextcloud.k8s.domingo.link
    secretName: nextcloud-ingress-tls
  rules:
    - host: nextcloud.k8s.domingo.link
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nextcloud
                port:
                  number: 8080

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-nfs
  namespace: nextcloud
spec:
  storageClassName: hostpath
  capacity:
    storage: 6T
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/raid0/nextcloud"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-nfs
  namespace: nextcloud
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: hostpath
  resources:
    requests:
      storage: 6T
  volumeName: nextcloud-nfs

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-nfs-data
  namespace: nextcloud
spec:
  storageClassName: hostpath
  capacity:
    storage: 6T
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/raid0/nextcloud/mariadb"
  

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-nfs-data
  namespace: nextcloud
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: hostpath
  resources:
    requests:
      storage: 6T
  volumeName: nextcloud-nfs-data

{{- end -}}
