{{- if .Values.apps.podGateway.enabled -}}

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pod-gateway
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: core
  source:
    repoURL: https://angelnu.github.io/helm-charts
    targetRevision: 6.0.0
    chart: pod-gateway
    helm:
      values: |
        {{- .Values.apps.podGateway.valuesOverrides | toYaml | nindent 8 }}

  destination:
    server: https://kubernetes.default.svc
    namespace: pod-gateway

  # Sync policy
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true 
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    retry:
      limit: 3
      backoff:
        duration: 30s
  revisionHistoryLimit: 3

{{- end -}}
