coreSourceRepos:
  - https://github.com/dom38/*
coreOverrides: {}

argo-cd:
  controller:
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi
