apps:

  certManager:
    enabled: true
    valuesOverrides:
      installCRDs: true

  ingressNginx:
    enabled: true
    valuesOverrides:
      controller:
        dnsPolicy: ClusterFirstWithHostNet
        hostNetwork: true
        kind: "DaemonSet"
        ingressClassResource:
          name: nginx
          enabled: true
          default: true
          controllerValue: "k8s.io/ingress-nginx"
        ingressClass: nginx
        watchIngressWithoutClass: true
        publishService:
          enabled: false
        service:
          enabled: true
          type: ClusterIP
        metrics:
          enabled: false
        serviceAccount:
          create: true
        admissionWebhooks:
          enabled: false

  istioBase:
    enabled: false

  istiod:
    enabled: false

  istioGateway:
    enabled: false

  mediaServerAddons:
    enabled: false
  
  mediaServer:
    enabled: false

  metricsServer:
    enabled: true
    valuesOverrides:
      args:
      - '--kubelet-insecure-tls'
