apps:
  istioBase:
    enabled: true
  istiod:
    enabled: true
  istioGateway:
    enabled: true
    valuesOverride:
      service:
        loadBalancerIP: "192.168.128.5"
        annotations:
          metallb.universe.tf/address-pool: homelab-addresspool
