apiVersion: v1
kind: Service
metadata:
  name: {{ include "deluge-ovpn.fullname" . }}
  labels:
    {{- include "deluge-ovpn.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 8118
      targetPort: privoxy
      protocol: TCP
      name: privoxy
  selector:
    {{- include "deluge-ovpn.selectorLabels" . | nindent 4 }}
