apiVersion: v1
kind: Service
metadata:
  name: {{ include "qbittorrentvpn.fullname" . }}
  labels:
    {{- include "qbittorrentvpn.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
    - port: 8999
      targetPort: listen
      protocol: TCP
      name: listen
    - port: 8999
      targetPort: listenudp
      protocol: TCP
      name: listenudp
  selector:
    {{- include "qbittorrentvpn.selectorLabels" . | nindent 4 }}
