apiVersion: v1
kind: PersistentVolume
metadata:
  name: qbittorrent-torrent-nfs
  namespace: qbittorrentvpn
spec:
  capacity:
    storage: 6T
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.128.2
    path: "/raid0/torrents"
  mountOptions:
    - nfsvers=4.2

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-torrent-nfs
  namespace: qbittorrentvpn
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 6T
  volumeName: qbittorrent-torrent-nfs

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: qbittorrent-config-nfs
  namespace: qbittorrentvpn
spec:
  capacity:
    storage: 6T
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.128.2
    path: "/raid0/config/qbittorrent"
  mountOptions:
    - nfsvers=4.2

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-config-nfs
  namespace: qbittorrentvpn
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 6T
  volumeName: qbittorrent-config-nfs
