apiVersion: v1
kind: PersistentVolume
metadata:
  name: qbittorrent-torrent-nfs
  namespace: qbittorrentvpn
spec:
  storageClassName: hostpath
  capacity:
    storage: 6T
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/raid0/torrents"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-torrent-nfs
  namespace: qbittorrentvpn
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 6T
  volumeName: qbittorrent-torrent-nfs

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: qbittorrent-config-nfs
  namespace: qbittorrentvpn
spec:
  storageClassName: hostpath
  capacity:
    storage: 6T
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/raid0/config/qbittorrentvpn"
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-config-nfs
  namespace: qbittorrentvpn
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 6T
  volumeName: qbittorrent-config-nfs
