replicaCount: 1

image:
  repository: markusmcnugen/qbittorrentvpn
  pullPolicy: IfNotPresent
  tag: latest

serviceAccount:
  create: false

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/whitelist-source-range: 87.75.106.7/32,192.168.128.1/32
  hosts:
    - host: qbittorrentvpn.k8s.domingo.link
      paths:
        - path: /
          pathType: Prefix
  tls:
  - hosts:
    - qbittorrentvpn.k8s.domingo.link
    secretName: qbittorrentvpn-ingress-tls

resources:
  limits:
    cpu: 1000m
    memory: 5000Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80
