{{- if .Values.apps.crossplaneGkeCluster.enabled -}}

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-gke-cluster
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "25"
spec:
  project: core
  source:
    repoURL: https://github.com/dom38/homelab.git
    targetRevision: main
    path: helm-charts/crossplane-gke-cluster
    helm:
      values: |
        {{- .Values.apps.crossplaneGkeCluster.valuesOverrides | toYaml | nindent 8 }}

  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane-gke-cluster

  # Sync policy
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true 
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    retry:
      limit: 3
      backoff:
        duration: 30s
  revisionHistoryLimit: 3

{{- end }}
