{{- if .Values.apps.bazarr.enabled -}}

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bazarr
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "15"
spec:
  project: core
  source:
    repoURL: https://aste88.github.io/helm-charts
    targetRevision: 11.0.0
    chart: bazarr
    helm:
      values: |
        {{- .Values.apps.bazarr.valuesOverrides | toYaml | nindent 8 }}

  destination:
    server: https://kubernetes.default.svc
    namespace: bazarr

  # Sync policy
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true 
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    retry:
      limit: 3
      backoff:
        duration: 30s
  revisionHistoryLimit: 3

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bazarr-ingress
  namespace: bazarr
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/whitelist-source-range: 86.1.85.130/32,192.168.128.1/32
spec:
  tls:
  - hosts:
    - bazarr.k8s.domingo.link
    secretName: bazarr-ingress-tls
  rules:
    - host: bazarr.k8s.domingo.link
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bazarr
                port:
                  number: 6767

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: bazarr-nfs
  namespace: bazarr
spec:
  storageClassName: hostpath
  capacity:
    storage: 6T
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/raid0/media-server"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bazarr-nfs
  namespace: bazarr
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 6T
  volumeName: bazarr-nfs

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: bazarr-config-nfs
  namespace: bazarr
spec:
  storageClassName: hostpath
  capacity:
    storage: 6T
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/raid0/config/bazarr"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bazarr-config-nfs
  namespace: bazarr
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: hostpath
  resources:
    requests:
      storage: 6T
  volumeName: bazarr-config-nfs
{{- end -}}
