{{- if .Values.apps.ombi.enabled -}}

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ombi
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "15"
spec:
  project: core
  source:
    repoURL: https://aste88.github.io/helm-charts
    targetRevision: 12.0.0
    chart: ombi
    helm:
      values: |
        {{- .Values.apps.ombi.valuesOverrides | toYaml | nindent 8 }}

  destination:
    server: https://kubernetes.default.svc
    namespace: ombi

  # Sync policy
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true 
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    retry:
      limit: 3
      backoff:
        duration: 30s
  revisionHistoryLimit: 3

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ombi-ingress
  namespace: ombi
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/whitelist-source-range: 86.1.85.130/32,192.168.128.1/32
spec:
  tls:
  - hosts:
    - ombi.k8s.domingo.link
    secretName: ombi-ingress-tls
  rules:
    - host: ombi.k8s.domingo.link
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ombi
                port:
                  number: 3579


{{- end -}}
