{{- if .Values.apps.qbittorrentvpn.enabled -}}

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: qbittorrentvpn
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "15"
spec:
  project: core
  source:
    repoURL: https://github.com/dom38/homelab.git
    targetRevision: main
    path: helm-charts/qbittorrentvpn
    helm:
      values: |
        {{- .Values.apps.qbittorrentvpn.valuesOverrides | toYaml | nindent 8 }}

  destination:
    server: https://kubernetes.default.svc
    namespace: qbittorrentvpn
  
  ignoreDifferences:
  - kind: Secret
    name: open-vpn-configuration
    namespace: qbittorrentvpn
    jsonPointers:
    - /data
    - /data/*

  # Sync policy
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true 
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    retry:
      limit: 3
      backoff:
        duration: 30s
  revisionHistoryLimit: 3

---

{{- end -}}
