{{- if .Values.apps.sonarr.enabled -}}

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sonarr
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "15"
spec:
  project: core
  source:
    repoURL: https://k8s-at-home.com/charts/
    targetRevision: 16.3.2
    chart: sonarr
    helm:
      values: |
        {{- .Values.apps.sonarr.valuesOverrides | toYaml | nindent 8 }}

  destination:
    server: https://kubernetes.default.svc
    namespace: sonarr

  # Sync policy
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true 
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    retry:
      limit: 3
      backoff:
        duration: 30s
  revisionHistoryLimit: 3

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sonarr-ingress
  namespace: sonarr
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/whitelist-source-range: 90.251.123.93/32,192.168.128.1/32
spec:
  tls:
  - hosts:
    - sonarr.k8s.domingo.link
    secretName: sonarr-ingress-tls
  rules:
    - host: sonarr.k8s.domingo.link
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sonarr
                port:
                  number: 8989

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarr-nfs
  namespace: sonarr
spec:
  storageClassName: hostpath
  capacity:
    storage: 6T
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/raid0/media-server"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-nfs
  namespace: sonarr
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 6T
  volumeName: sonarr-nfs

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarr-config-nfs
  namespace: sonarr
spec:
  storageClassName: hostpath
  capacity:
    storage: 6T
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/raid0/config/sonarr"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-config-nfs
  namespace: sonarr
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: hostpath
  resources:
    requests:
      storage: 6T
  volumeName: sonarr-config-nfs

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarr-torrent-nfs
  namespace: sonarr
spec:
  storageClassName: hostpath
  capacity:
    storage: 6T
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/raid0/torrents"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-torrent-nfs
  namespace: sonarr
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 6T
  volumeName: sonarr-torrent-nfs

{{- end -}}
