{{- if .Values.apps.tautulli.enabled -}}

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tautulli
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "15"
spec:
  project: core
  source:
    repoURL: https://charts.truecharts.org
    targetRevision: 12.0.2
    chart: tautulli
    helm:
      values: |
        {{- .Values.apps.tautulli.valuesOverrides | toYaml | nindent 8 }}

  destination:
    server: https://kubernetes.default.svc
    namespace: tautulli

  # Sync policy
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true 
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    retry:
      limit: 3
      backoff:
        duration: 30s
  revisionHistoryLimit: 3

---

# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: tautulli-ingress
#   namespace: tautulli
#   annotations:
#     cert-manager.io/cluster-issuer: letsencrypt-prod
# spec:
#   tls:
#   - hosts:
#     - tautulli.k8s.domingo.link
#     secretName: tautulli-ingress-tls
#   rules:
#     - host: tautulli.k8s.domingo.link
#       http:
#         paths:
#           - path: /
#             pathType: Prefix
#             backend:
#               service:
#                 name: tautulli
#                 port:
#                   number: 32400


{{- end -}}
