{{- if .Values.apps.transmission.enabled -}}

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: transmission
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "15"
spec:
  project: core
  source:
    repoURL: https://geek-cookbook.github.io/charts/
    targetRevision: 8.4.3
    chart: transmission
    helm:
      values: |
        {{- .Values.apps.transmission.valuesOverrides | toYaml | nindent 8 }}

  destination:
    server: https://kubernetes.default.svc
    namespace: transmission

  # Sync policy
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    retry:
      limit: 3
      backoff:
        duration: 30s
  revisionHistoryLimit: 3

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: transmission-ingress
  namespace: transmission
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/whitelist-source-range: 90.251.123.93/32,192.168.128.1/32
spec:
  tls:
  - hosts:
    - transmission.k8s.domingo.link
    secretName: transmission-ingress-tls
  rules:
    - host: transmission.k8s.domingo.link
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: transmission
                port:
                  number: 9091

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: transmission-nfs
  namespace: transmission
spec:
  capacity:
    storage: 6T
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.128.2
    path: "/raid0/torrents"
  mountOptions:
    - nfsvers=4.2

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transmission-nfs
  namespace: transmission
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 6T
  volumeName: transmission-nfs

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: transmission-config-nfs
  namespace: transmission
spec:
  capacity:
    storage: 6T
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.128.2
    path: "/raid0/config/transmission"
  mountOptions:
    - nfsvers=4.2

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transmission-config-nfs
  namespace: transmission
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 6T
  volumeName: transmission-config-nfs

{{- end -}}
