replicaCount: 1

image:
  repository: binhex/arch-delugevpn
  pullPolicy: IfNotPresent
  tag: 2.1.1-1-02

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false

service:
  type: ClusterIP
  port: 8112

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/whitelist-source-range: 87.75.106.7/32,192.168.128.1/32
  hosts:
    - host: deluge-ovpn.k8s.domingo.link
      paths:
        - path: /
          pathType: Prefix
  tls:
  - hosts:
    - deluge-ovpn.k8s.domingo.link
    secretName: deluge-ovpn-ingress-tls

resources:
  limits:
    cpu: 500m
    memory: 500Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
