apiVersion: container.gcp.upbound.io/v1beta1
kind: Cluster
metadata:
  name: test-cluster
spec:
  providerConfigRef:
    name: gcp-config
  forProvider:
    initialNodeCount: 1
    initialClusterVersion: "1.27"
    location: europe-west1-b
    autoscaling:
      autoprovisioningNodePoolDefaults:
        serviceAccount: sa-test
    networkConfig:
      enableIntraNodeVisibility: true
    loggingService: logging.googleapis.com/kubernetes
    monitoringService: monitoring.googleapis.com/kubernetes
    network: "default"
  writeConnectionSecretToRef:
    namespace: {{ .Release.Namespace }}
    name: gke-conn
