apps:

  emby:
    enabled: true
    valuesOverrides:
      automountServiceAccountToken: false
      resources:
        requests: 
          cpu: 2000m
          memory: 2000Mi
        limits:
          cpu: 8000m
          memory: 4000Mi
      image:
        repository: ghcr.io/onedr0p/emby
        tag: 4.7.11.0
      persistence:
        config:
          enabled: true
          existingClaim: emby-config-nfs
          accessMode: ReadWriteMany
          size: 6T
          type: pvc
        data:
          enabled: true
          existingClaim: emby-nfs
          accessMode: ReadWriteMany
          size: 6T
          type: pvc
  
  jellyfin:
    enabled: false
    valuesOverrides:
      automountServiceAccountToken: false
      resources:
        requests: 
          cpu: 2000m
          memory: 2000Mi
        limits:
          cpu: 8000m
          memory: 4000Mi
      image:
        tag: 10.8.10
      persistence:
        config:
          enabled: true
          existingClaim: jellyfin-config-nfs
          accessMode: ReadWriteMany
          size: 6T
          type: pvc
        data:
          enabled: true
          existingClaim: jellyfin-nfs
          accessMode: ReadWriteMany
          size: 6T
          type: pvc

  plex:
    enabled: true
    valuesOverrides:
      automountServiceAccountToken: false
      resources:
        requests: 
          cpu: 2000m
          memory: 2000Mi
        limits:
          cpu: 8000m
          memory: 4000Mi
      image:
        tag: 1.32.3
        repository: linuxserver/plex
      env:
      - name: PLEX_CLAIM
        value: claim-ctv1GqKuDHjT7uHTyf41
      persistence:
        config:
          enabled: true
          existingClaim: plex-config-nfs
          accessMode: ReadWriteOnce
          size: 6T
          type: pvc
        data:
          enabled: true
          existingClaim: plex-nfs
          accessMode: ReadWriteOnce
          size: 6T
          type: pvc
