apps:

  emby:
    enabled: true
    valuesOverrides:
      # securityContext:
      #   runAsUser: 1001
      #   runAsGroup: 1001
      #   fsGroup: 1001
      image:
        repository: ghcr.io/onedr0p/emby
        tag: 4.7.11.0
      persistence:
        config:
          enabled: true
          existingClaim: emby-config-nfs
          accessMode: ReadWriteMany
          size: 6T
          type: pvc
        data:
          enabled: true
          existingClaim: emby-nfs
          accessMode: ReadWriteMany
          size: 6T
          type: pvc
  
  jellyfin:
    enabled: true
    valuesOverrides:
      image:
        tag: 10.8.10
      persistence:
        config:
          enabled: true
          existingClaim: jellyfin-config-nfs
          accessMode: ReadWriteMany
          size: 6T
          type: pvc
        data:
          enabled: true
          existingClaim: jellyfin-nfs
          accessMode: ReadWriteMany
          size: 6T
          type: pvc

  plex:
    enabled: true
    valuesOverrides:
      resources:
        requests: 
          cpu: 2
          memory: 2000
        limits:
          cpu: 4
          memory: 4000
      image:
        tag: 1.32.0
      env:
      - name: PLEX_CLAIM
        value: claim-ctv1GqKuDHjT7uHTyf41
      persistence:
        config:
          enabled: true
          existingClaim: plex-config-nfs
          accessMode: ReadWriteMany
          size: 6T
          type: pvc
        data:
          enabled: true
          existingClaim: plex-nfs
          accessMode: ReadWriteMany
          size: 6T
          type: pvc
