apps:

  emby:
    enabled: true
    valuesOverrides:
      securityContext:
        privileged: true
      image:
        repository: ghcr.io/onedr0p/emby
        tag: 4.7.10.0
      persistence:
        config:
          enabled: false
          existingClaim: emby-config-nfs
          accessMode: ReadWriteMany
          size: 6T
          type: pvc
        data:
          enabled: true
          existingClaim: emby-nfs
          accessMode: ReadWriteMany
          size: 6T
          type: pvc
  
  jellyfin:
    enabled: true
    valuesOverrides:
      persistence:
        config:
          enabled: true
          existingClaim: jellyfin-config-nfs
          accessMode: ReadWriteMany
          size: 6T
          type: pvc
        data:
          enabled: true
          existingClaim: jellyfin-nfs
          accessMode: ReadWriteMany
          size: 6T
          type: pvc

  plex:
    enabled: true
    valuesOverrides:
      env:
      - name: PLEX_CLAIM
        value: claim-ctv1GqKuDHjT7uHTyf41
      persistence:
        config:
          enabled: true
          existingClaim: plex-config-nfs
          accessMode: ReadWriteMany
          size: 6T
          type: pvc
        data:
          enabled: true
          existingClaim: plex-nfs
          accessMode: ReadWriteMany
          size: 6T
          type: pvc
