{{- if .Values.apps.emby.enabled -}}

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: emby
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "15"
spec:
  project: core
  source:
    repoURL: https://k8s-at-home.com/charts/
    targetRevision: 3.4.2
    chart: emby
    helm:
      values: |
        {{- .Values.apps.emby.valuesOverrides | toYaml | nindent 8 }}

  destination:
    server: https://kubernetes.default.svc
    namespace: emby

  # Sync policy
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true 
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    retry:
      limit: 3
      backoff:
        duration: 30s
  revisionHistoryLimit: 3

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: emby-ingress
  namespace: emby
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - emby.k8s.domingo.link
    secretName: emby-ingress-tls
  rules:
    - host: emby.k8s.domingo.link
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: emby
                port:
                  number: 8096

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: emby-nfs
  namespace: emby
spec:
  capacity:
    storage: 6T
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.128.2
    path: "/raid0/media-server"
  mountOptions:
    - nfsvers=4.2

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: emby-nfs
  namespace: emby
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 6T
  volumeName: emby-nfs

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: emby-config-nfs
  namespace: emby
spec:
  storageClassName: hostpath
  capacity:
    storage: 6T
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/raid0/config/emby"

# kind: StorageClass
# apiVersion: storage.k8s.io/v1
# metadata:
#   name: emby-config
# provisioner: microk8s.io/hostpath
# reclaimPolicy: Delete
# parameters:
#   pvDir: /mnt/raid0/config/emby
# volumeBindingMode: WaitForFirstConsumer

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: emby-config-nfs
  namespace: emby
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 6T
{{- end -}}
