{{- if .Values.apps.jellyfin.enabled -}}

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jellyfin
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "15"
spec:
  project: core
  source:
    repoURL: https://k8s-at-home.com/charts/
    targetRevision: 9.5.3
    chart: jellyfin
    helm:
      values: |
        {{- .Values.apps.jellyfin.valuesOverrides | toYaml | nindent 8 }}

  destination:
    server: https://kubernetes.default.svc
    namespace: jellyfin

  # Sync policy
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true 
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    retry:
      limit: 3
      backoff:
        duration: 30s
  revisionHistoryLimit: 3

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jellyfin-ingress
  namespace: jellyfin
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - jellyfin.k8s.domingo.link
    secretName: jellyfin-ingress-tls
  rules:
    - host: jellyfin.k8s.domingo.link
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jellyfin
                port:
                  number: 8096

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-nfs
  namespace: jellyfin
spec:
storageClassName: hostpath
  capacity:
    storage: 6T
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/raid0/media-server"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-nfs
  namespace: jellyfin
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 6T
  volumeName: jellyfin-nfs

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-config-nfs
  namespace: jellyfin
spec:
  storageClassName: hostpath
  capacity:
    storage: 6T
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/raid0/config/jellyfin"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config-nfs
  namespace: jellyfin
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: hostpath
  resources:
    requests:
      storage: 6T
  volumeName: jellyfin-config-nfs
{{- end -}}
