{{- if .Values.apps.plex.enabled -}}

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plex
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: core
  source:
    repoURL: https://charts.truecharts.org
    targetRevision: 11.0.2
    chart: plex
    helm:
      values: |
        {{- .Values.apps.plex.valuesOverrides | toYaml | nindent 8 }}

  destination:
    server: https://kubernetes.default.svc
    namespace: plex

  # Sync policy
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true 
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    retry:
      limit: 3
      backoff:
        duration: 30s
  revisionHistoryLimit: 3

{{- end -}}
