{{- if .Values.apps.plex.enabled -}}

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plex
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "15"
spec:
  project: core
  source:
    repoURL: https://aste88.github.io/helm-charts
    targetRevision: 7.0.0
    chart: plex
    helm:
      values: |
        {{- .Values.apps.plex.valuesOverrides | toYaml | nindent 8 }}

  destination:
    server: https://kubernetes.default.svc
    namespace: plex

  # Sync policy
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true 
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    retry:
      limit: 3
      backoff:
        duration: 30s
  revisionHistoryLimit: 3

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: plex-ingress
  namespace: plex
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - plex.k8s.domingo.link
    secretName: plex-ingress-tls
  rules:
    - host: plex.k8s.domingo.link
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: plex
                port:
                  number: 32400

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-nfs
  namespace: plex
spec:
  capacity:
    storage: 6T
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.128.2
    path: "/raid0/media-server"
  mountOptions:
    - nfsvers=4.2

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-nfs
  namespace: plex
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 6T
  volumeName: plex-nfs

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-config-nfs
  namespace: plex
spec:
  storageClassName: hostpath
  capacity:
    storage: 6T
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/raid0/config/plex"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-config-nfs
  namespace: plex
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 6T
  volumeName: plex-config-nfs

{{- end -}}
