apps:

  bazarr:
    enabled: true
    valuesOverrides:
      persistence:
        config:
          enabled: true
          existingClaim: bazarr-config-nfs
          accessMode: ReadWriteMany
          size: 6T
          type: pvc
        data:
          enabled: true
          existingClaim: bazarr-nfs
          accessMode: ReadWriteMany
          size: 6T
          type: pvc
  
  delugeOvpn:
    enabled: true

  jackett:
    enabled: true
    valuesOverrides:
      replicaCount: 1
      image:
        repository: "dyonr/jackettvpn" # Special image to use Jackett over a VPN
        tag: "latest"
        pullPolicy: IfNotPresent
      env:
        - name: VPN_ENABLED
          value: "yes" # Enable Jackett over VPN
        - name: VPN_TYPE
          value: "openvpn" # Enable Jackett over VPN
        - name: LAN_NETWORK
          value: "10.0.0.0/8"
        - name: CREATE_TUN_DEVICE
          value: "true" # Needed for VPN
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: WEBUI_PORT
          value: "80"
      service:
        type: ClusterIP
        port: 80
      volumes:
        - name: "config"
          persistentVolumeClaim:
            claimName: "jackett-config-nfs"
        - name: "downloads"
          persistentVolumeClaim:
            claimName: "jackett-nfs"
      volumeMounts:
        - name: "config"
          mountPath: "/config"
        - name: "downloads"
          mountPath: "/blackhole"
      securityContext:
        privileged: true

  ombi:
    enabled: true
    valuesOverrides:
      persistence:
        config:
          enabled: true
          existingClaim: ombi-config-nfs
          accessMode: ReadWriteMany
          size: 6T
          type: pvc

  qbittorrentvpn:
    enabled: true

  radarr:
    enabled: true
    valuesOverrides:
      persistence:
        config:
          enabled: true
          existingClaim: radarr-config-nfs
          accessMode: ReadWriteMany
          size: 6T
          type: pvc
        data:
          enabled: true
          existingClaim: radarr-nfs
          accessMode: ReadWriteMany
          size: 6T
          type: pvc
  
  sonarr:
    enabled: true
    valuesOverrides:
      persistence:
        config:
          enabled: true
          existingClaim: sonarr-config-nfs
          accessMode: ReadWriteMany
          size: 6T
          type: pvc
        data:
          enabled: true
          existingClaim: sonarr-nfs
          accessMode: ReadWriteMany
          size: 6T
          type: pvc

  tautulli:
    enabled: true

  transmission:
    enabled: true
    valuesOverrides:
      probes:
        liveness:
          enabled: false
        readiness:
          enabled: false
        startup:
          enabled: false
      persistence:
        config:
          enabled: true
          existingClaim: transmission-config-nfs
          accessMode: ReadWriteMany
          size: 6T
          type: pvc
        torrents:
          enabled: true
          existingClaim: transmission-nfs
          accessMode: ReadWriteMany
          size: 6T
          type: pvc
