apps:

  bazarr:
    enabled: true
    valuesOverrides:
      image:
        tag: latest
        repository: linuxserver/bazarr
      persistence:
        config:
          enabled: true
          existingClaim: bazarr-config-nfs
          accessMode: ReadWriteOnce
          size: 6T
          type: pvc
        data:
          enabled: true
          existingClaim: bazarr-nfs
          accessMode: ReadWriteOnce
          size: 6T
          type: pvc
  
  calibre:
    enabled: true
    valuesOverrides:
      image:
        tag: latest
        repository: linuxserver/calibre
      persistence:
        config:
          enabled: true
          existingClaim: calibre-config-nfs
          accessMode: ReadWriteOnce
          size: 6T
          type: pvc
        data:
          enabled: true
          existingClaim: calibre-nfs
          accessMode: ReadWriteOnce
          size: 6T
          type: pvc
        torrents:
          enabled: true
          existingClaim: calibre-torrent-nfs
          accessMode: ReadWriteOnce
          size: 6T
          type: pvc

  delugeOvpn:
    enabled: false

  jackett:
    enabled: true
    valuesOverrides:
      image:
        repository: linuxserver/jackett
        tag: latest
      persistence:
        config:
          enabled: true
          existingClaim: jackett-config-nfs
          accessMode: ReadWriteOnce
          size: 6T
          type: pvc
        torrentblackhole:
          enabled: true
          existingClaim: jackett-nfs
          accessMode: ReadWriteOnce
          size: 6T
          type: pvc
          mountPath: /downloads
      addons:
        vpn:
          enabled: true
          type: openvpn
          env:
            - name: DNS
              value: "8.8.8.8"
          openvpn:
            authSecret: openvpn
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - SYS_MODULE
          configFileSecret: openvpn

  ombi:
    enabled: true
    valuesOverrides:
      image:
        tag: 4.33.0-development
      persistence:
        config:
          enabled: true
          existingClaim: ombi-config-nfs
          accessMode: ReadWriteOnce
          size: 6T
          type: pvc

  qbittorrentvpn:
    enabled: true

  radarr:
    enabled: true
    valuesOverrides:
      image:
        tag: latest
        repository: linuxserver/radarr
      persistence:
        config:
          enabled: true
          existingClaim: radarr-config-nfs
          accessMode: ReadWriteOnce
          size: 6T
          type: pvc
        data:
          enabled: true
          existingClaim: radarr-nfs
          accessMode: ReadWriteOnce
          size: 6T
          type: pvc
        torrents:
          enabled: true
          existingClaim: radarr-torrent-nfs
          accessMode: ReadWriteOnce
          size: 6T
          type: pvc

  readarr:
    enabled: true
    valuesOverrides:
      image:
        tag: develop
        repository: linuxserver/readarr
      persistence:
        config:
          enabled: true
          existingClaim: readarr-config-nfs
          accessMode: ReadWriteOnce
          size: 6T
          type: pvc
        data:
          enabled: true
          existingClaim: readarr-nfs
          accessMode: ReadWriteOnce
          size: 6T
          type: pvc
        torrents:
          enabled: true
          existingClaim: readarr-torrent-nfs
          accessMode: ReadWriteOnce
          size: 6T
          type: pvc
  
  sonarr:
    enabled: true
    valuesOverrides:
      image:
        tag: latest
        repository: linuxserver/sonarr
      persistence:
        config:
          enabled: true
          existingClaim: sonarr-config-nfs
          accessMode: ReadWriteOnce
          size: 6T
          type: pvc
        data:
          enabled: true
          existingClaim: sonarr-nfs
          accessMode: ReadWriteOnce
          size: 6T
          type: pvc
        torrents:
          enabled: true
          existingClaim: sonarr-torrent-nfs
          accessMode: ReadWriteOnce
          size: 6T
          type: pvc

  tautulli:
    enabled: false
    valuesOverrides:
      persistence:
          config:
            enabled: true
            existingClaim: tautulli-config-nfs
            accessMode: ReadWriteOnce
            size: 6T
            type: pvc

  transmission:
    enabled: false

  unpackerr:
    enabled: true
    valuesOverrides:
      image:
        tag: latest
        repository: golift/unpackerr
      env:
        UN_SONARR_0_URL: https://sonarr.k8s.domingo.link
        UN_SONARR_0_API_KEY: 2503e39a934746f096b421ae3c7c8edd
        UN_SONARR_0_PATHS_0: /torrents
        UN_SONARR_0_PROTOCOLS: torrent
        UN_SONARR_0_TIMEOUT: 10s
        UN_SONARR_0_DELETE_DELAY: 5m
        UN_SONARR_0_DELETE_ORIG: false
        UN_SONARR_0_SYNCTHING: false
      service:
        main:
          enabled: false
      persistence:
        config:
          enabled: true
          existingClaim: unpackerr-config-nfs
          accessMode: ReadWriteOnce
          size: 6T
          type: pvc
        data:
          enabled: true
          existingClaim: unpackerr-nfs
          accessMode: ReadWriteOnce
          size: 6T
          type: pvc
        torrents:
          enabled: true
          existingClaim: unpackerr-torrent-nfs
          accessMode: ReadWriteOnce
          size: 6T
          type: pvc
