apps:

  bazarr:
    enabled: true
  
  ombi:
    enabled: true
  
  # Needs additional config, API keys for connnecting to Notifiarr + TMDb
  plexMetaManager:
    enabled: false

  plexUtills:
    enabled: true

  radarr:
    enabled: true
  
  sonarr:
    enabled: true

  tautulli:
    enabled: true

  transmission:
    enabled: true
    valuesOverrides:
      extraVolumes:
      - name: open-vpn-config
        secret:
          secretName: open-vpn-configuration
          optional: false
      extraVolumeMounts:
      - name: open-vpn-config
        mountPath: /etc/openvpn/custom/
        defaultMode: 777
