apps:

  bazarr:
    enabled: true
    valuesOverrides:
      persistence:
        config:
          enabled: true
          existingClaim: bazarr-config-nfs
          accessMode: ReadWriteMany
          size: 6T
          type: pvc
        data:
          enabled: true
          existingClaim: bazarr-nfs
          accessMode: ReadWriteMany
          size: 6T
          type: pvc
  
  delugeOvpn:
    enabled: true

  ombi:
    enabled: true
    valuesOverrides:
      persistence:
        config:
          enabled: true
          existingClaim: ombi-config-nfs
          accessMode: ReadWriteMany
          size: 6T
          type: pvc

  qbittorrentvpn:
    enabled: true

  radarr:
    enabled: true
    valuesOverrides:
      persistence:
        config:
          enabled: true
          existingClaim: radarr-config-nfs
          accessMode: ReadWriteMany
          size: 6T
          type: pvc
        data:
          enabled: true
          existingClaim: radarr-nfs
          accessMode: ReadWriteMany
          size: 6T
          type: pvc
  
  sonarr:
    enabled: true
    valuesOverrides:
      persistence:
        config:
          enabled: true
          existingClaim: sonarr-config-nfs
          accessMode: ReadWriteMany
          size: 6T
          type: pvc
        data:
          enabled: true
          existingClaim: sonarr-nfs
          accessMode: ReadWriteMany
          size: 6T
          type: pvc

  tautulli:
    enabled: true

  transmission:
    enabled: true
    valuesOverrides:
      probes:
        liveness:
          enabled: false
        readiness:
          enabled: false
        startup:
          enabled: false
      persistence:
        config:
          enabled: true
          existingClaim: transmission-config-nfs
          accessMode: ReadWriteMany
          size: 6T
          type: pvc
        torrents:
          enabled: true
          existingClaim: transmission-nfs
          accessMode: ReadWriteMany
          size: 6T
          type: pvc
