apps:

  bazarr:
    enabled: true
  
  ombi:
    enabled: true
  
  # Needs additional config, API keys for connnecting to Notifiarr + TMDb
  plexMetaManager:
    enabled: false

  plexUtills:
    enabled: true

  radarr:
    enabled: true
  
  sonarr:
    enabled: true

  tautulli:
    enabled: true

  transmission:
    enabled: true
    valuesOverrides:
      initContainers:
      - name: move-secrets
        image: busybox:1.29.2
        command:
        - "cp" 
        - "/openvpnconfig/*"
        - "/etc/openvpn/custom/."
        - "&&"
        - "ls"
        - "/etc/openvpn/custom/"
        volumeMounts:
        - name: config
          mountPath: /etc/openvpn/custom/
        - name: open-vpn-config
          mountPath: /openvpnconfig/
        securityContext:
          runAsUser: 568
          runAsGroup: 568
      extraVolumes:
      - name: config
        emptyDir: {}
      - name: open-vpn-config
        secret:
          secretName: open-vpn-configuration
          optional: false
      extraVolumeMounts:
      - name: config
        mountPath: /etc/openvpn/custom/
        defaultMode: 777
