apps:

  ombi:
    enabled: true
  
  # Needs additional config, API keys for connnecting to Notifiarr + TMDb
  plexMetaManager:
    enabled: false

  plexUtills:
    enabled: true

  tautulli:
    enabled: true
