apps:

  bazarr:
    enabled: true
  
  ombi:
    enabled: true
  
  # Needs additional config, API keys for connnecting to Notifiarr + TMDb
  plexMetaManager:
    enabled: false

  plexUtills:
    enabled: true

  radarr:
    enabled: true
  
  sonarr:
    enabled: true

  tautulli:
    enabled: true

  transmission:
    enabled: true
